services:
  app:
    build: .
    container_name: mcp_kalia
    volumes:
      - .:/app
      - ./log:/app/log
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
    network_mode: "bridge" 